server:
  port: 8088

spring:
  application:
    name: portal-consumer
  cloud:
    servicecomb:
      discovery:
        enabled: true
        address: http://127.0.0.1:30100
        appName: discovery
        serviceName: portal-consumer
        version: 0.0.1